version: "3.8"

services:
  app:
    build:
      context: ./app
    user: ${UID}:${GID}
    restart: unless-stopped
    container_name: fastapi
    environment:
      - FASTAPI_PORT=${FASTAPI_PORT}
    volumes:
      - ./app:/app
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}