version: "3.8"

services:
  app:
    build:
      context: ./app
    user: ${UID}:${GID}
    restart: unless-stopped
    container_name: fastapi
    environment:
      - FASTAPI_PORT=${FASTAPI_PORT}
    volumes:
      - ./app:/app
    ports:
      - ${FASTAPI_PORT}:${FASTAPI_PORT}

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    environment:
      - FASTAPI_PORT=${FASTAPI_PORT}
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml