version: "3.8"

services:
  app:
    build:
      context: ./app
    user: ${UID}:${GID}
    restart: unless-stopped
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml